package com.testapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Data class representing a Task entity in the Room database.
 *
 * This class defines the structure of the Task entity, which includes an
 * auto-generated primary key and a title.
 *
 * @property id The unique identifier for the Task. This field is auto-generated by the database.
 * @property title The title of the Task.
 */
@Entity
data class Task(
    @PrimaryKey(autoGenerate = true) val id: Int = 0, // Primary key with auto-generation
    val title: String // Title of the task
)

